{{- if .Values.trvs.enabled }}
apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "gcloud-cleanup.secret" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-cleanup.name" . }}
    helm.sh/chart: {{ include "gcloud-cleanup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: {{ .Values.trvs.app }}
  env: {{ .Values.trvs.env }}
  prefix: GCLOUD_CLEANUP
  pro: {{ .Values.trvs.pro }}
{{- end }}
